[package]
name = "ticket-marketplace-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs.workspace = true
gstd = { workspace = true, features = ["debug"] }
concert-app = { path = "../../concert/app" }

